# Copyright © 2018 DIG Development team. All rights reserved.

version: '3.0'
services:
    node:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "1337:1337"
        entrypoint: /app/run.sh
        tty: true
        restart: always
        environment:
        - NODE_ENV=production
