# Copyright © 2018 DIG Development team. All rights reserved.

version: '3.0'
services:
    node:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./:/DIGBot
        entrypoint: /app/run.sh
        tty: true
