# Copyright © 2018 DIG Development team. All rights reserved.

version: '3.0'
services:
    redis:
        image: "redis:alpine"
        volumes:
            - /data
    digbot:
        build: .
        volumes:
            # Links the local.json config to the container for local development
            - ./config/local.json:/usr/src/digbot/config/local.json
        depends_on:
          - redis
        tty: true
        environment:
            - REDIS_URL=redis://redis:6379

