version: '3.0'

services:
  redis:
    image: "redis:alpine"
    volumes:
      - /data
    ports:
      - 6379:6379
  mongo:
    image: mongo
    ports:
      - 27017:27017
  digbot:
    build: .
    volumes:
      # Links the local.json config to the container for local development
      - ./config/local.json:/usr/src/digbot/config/local.json
    depends_on:
      - redis
      - mongo
    tty: true
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/digbot

