version: '3.8'

services:
#  redis:
#    image: "redis:alpine"
#    volumes:
#      - /data
#    ports:
#      - 6379
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-pass}
      - MYSQL_DATABASE=${DB_NAME:-digbot}
      - MYSQL_USER=${DB_USER:-dig}
      - MYSQL_PASSWORD=${DB_PASS:-pass}
    ports:
      - 3306:3306
#  digbot:
#    build: .
#    volumes:
#      # Links the local.json config to the container for local development
#      - ./config/local.json:/usr/src/digbot/config/local.json
#    depends_on:
#      - redis
#      - mongo
#    tty: true
#    environment:
#      - REDIS_URL=redis://redis:6379
#      - MONGO_URL=mongodb://mongo:27017/digbot

